version: '3'
services:
  fxserver:
    build: .
    container_name: fxserver-txadmin
    ports:
      - "30120:30120/udp"
      - "30120:30120/tcp"
      - "40120:40120/tcp"
    environment:
      - DB_HOST=ip
      - DB_PORT=3306
      - DB_DATABASE=database_name
      - DB_USERNAME=username_not_root
      - DB_PASSWORD=password_db
